/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as DemoPulseadsVideoRouteImport } from './routes/demo.pulseads-video'
import { Route as DemoPanelproSmmRouteImport } from './routes/demo.panelpro-smm'
import { Route as DemoOrbitCrmRouteImport } from './routes/demo.orbit-crm'
import { Route as DemoLuxeLandingRouteImport } from './routes/demo.luxe-landing'
import { Route as DemoKartplusEcommerceRouteImport } from './routes/demo.kartplus-ecommerce'
import { Route as DemoFreshcartGroceryRouteImport } from './routes/demo.freshcart-grocery'
import { Route as DemoEduprimeLmsRouteImport } from './routes/demo.eduprime-lms'
import { Route as DemoBrandkitDesignRouteImport } from './routes/demo.brandkit-design'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public/config'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPulseadsVideoRoute = DemoPulseadsVideoRouteImport.update({
  id: '/demo/pulseads-video',
  path: '/demo/pulseads-video',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanelproSmmRoute = DemoPanelproSmmRouteImport.update({
  id: '/demo/panelpro-smm',
  path: '/demo/panelpro-smm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrbitCrmRoute = DemoOrbitCrmRouteImport.update({
  id: '/demo/orbit-crm',
  path: '/demo/orbit-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLuxeLandingRoute = DemoLuxeLandingRouteImport.update({
  id: '/demo/luxe-landing',
  path: '/demo/luxe-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKartplusEcommerceRoute = DemoKartplusEcommerceRouteImport.update({
  id: '/demo/kartplus-ecommerce',
  path: '/demo/kartplus-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFreshcartGroceryRoute = DemoFreshcartGroceryRouteImport.update({
  id: '/demo/freshcart-grocery',
  path: '/demo/freshcart-grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEduprimeLmsRoute = DemoEduprimeLmsRouteImport.update({
  id: '/demo/eduprime-lms',
  path: '/demo/eduprime-lms',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBrandkitDesignRoute = DemoBrandkitDesignRouteImport.update({
  id: '/demo/brandkit-design',
  path: '/demo/brandkit-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public/config',
  path: '/api/public/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/brandkit-design': typeof DemoBrandkitDesignRoute
  '/demo/eduprime-lms': typeof DemoEduprimeLmsRoute
  '/demo/freshcart-grocery': typeof DemoFreshcartGroceryRoute
  '/demo/kartplus-ecommerce': typeof DemoKartplusEcommerceRoute
  '/demo/luxe-landing': typeof DemoLuxeLandingRoute
  '/demo/orbit-crm': typeof DemoOrbitCrmRoute
  '/demo/panelpro-smm': typeof DemoPanelproSmmRoute
  '/demo/pulseads-video': typeof DemoPulseadsVideoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/public/config': typeof ApiPublicConfigRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/brandkit-design': typeof DemoBrandkitDesignRoute
  '/demo/eduprime-lms': typeof DemoEduprimeLmsRoute
  '/demo/freshcart-grocery': typeof DemoFreshcartGroceryRoute
  '/demo/kartplus-ecommerce': typeof DemoKartplusEcommerceRoute
  '/demo/luxe-landing': typeof DemoLuxeLandingRoute
  '/demo/orbit-crm': typeof DemoOrbitCrmRoute
  '/demo/panelpro-smm': typeof DemoPanelproSmmRoute
  '/demo/pulseads-video': typeof DemoPulseadsVideoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/public/config': typeof ApiPublicConfigRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/demo/brandkit-design': typeof DemoBrandkitDesignRoute
  '/demo/eduprime-lms': typeof DemoEduprimeLmsRoute
  '/demo/freshcart-grocery': typeof DemoFreshcartGroceryRoute
  '/demo/kartplus-ecommerce': typeof DemoKartplusEcommerceRoute
  '/demo/luxe-landing': typeof DemoLuxeLandingRoute
  '/demo/orbit-crm': typeof DemoOrbitCrmRoute
  '/demo/panelpro-smm': typeof DemoPanelproSmmRoute
  '/demo/pulseads-video': typeof DemoPulseadsVideoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/api/public/config': typeof ApiPublicConfigRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/demo/brandkit-design'
    | '/demo/eduprime-lms'
    | '/demo/freshcart-grocery'
    | '/demo/kartplus-ecommerce'
    | '/demo/luxe-landing'
    | '/demo/orbit-crm'
    | '/demo/panelpro-smm'
    | '/demo/pulseads-video'
    | '/services/$slug'
    | '/api/public/config'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/demo/brandkit-design'
    | '/demo/eduprime-lms'
    | '/demo/freshcart-grocery'
    | '/demo/kartplus-ecommerce'
    | '/demo/luxe-landing'
    | '/demo/orbit-crm'
    | '/demo/panelpro-smm'
    | '/demo/pulseads-video'
    | '/services/$slug'
    | '/api/public/config'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/sitemap.xml'
    | '/demo/brandkit-design'
    | '/demo/eduprime-lms'
    | '/demo/freshcart-grocery'
    | '/demo/kartplus-ecommerce'
    | '/demo/luxe-landing'
    | '/demo/orbit-crm'
    | '/demo/panelpro-smm'
    | '/demo/pulseads-video'
    | '/services/$slug'
    | '/api/public/config'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DemoBrandkitDesignRoute: typeof DemoBrandkitDesignRoute
  DemoEduprimeLmsRoute: typeof DemoEduprimeLmsRoute
  DemoFreshcartGroceryRoute: typeof DemoFreshcartGroceryRoute
  DemoKartplusEcommerceRoute: typeof DemoKartplusEcommerceRoute
  DemoLuxeLandingRoute: typeof DemoLuxeLandingRoute
  DemoOrbitCrmRoute: typeof DemoOrbitCrmRoute
  DemoPanelproSmmRoute: typeof DemoPanelproSmmRoute
  DemoPulseadsVideoRoute: typeof DemoPulseadsVideoRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pulseads-video': {
      id: '/demo/pulseads-video'
      path: '/demo/pulseads-video'
      fullPath: '/demo/pulseads-video'
      preLoaderRoute: typeof DemoPulseadsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panelpro-smm': {
      id: '/demo/panelpro-smm'
      path: '/demo/panelpro-smm'
      fullPath: '/demo/panelpro-smm'
      preLoaderRoute: typeof DemoPanelproSmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orbit-crm': {
      id: '/demo/orbit-crm'
      path: '/demo/orbit-crm'
      fullPath: '/demo/orbit-crm'
      preLoaderRoute: typeof DemoOrbitCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/luxe-landing': {
      id: '/demo/luxe-landing'
      path: '/demo/luxe-landing'
      fullPath: '/demo/luxe-landing'
      preLoaderRoute: typeof DemoLuxeLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/kartplus-ecommerce': {
      id: '/demo/kartplus-ecommerce'
      path: '/demo/kartplus-ecommerce'
      fullPath: '/demo/kartplus-ecommerce'
      preLoaderRoute: typeof DemoKartplusEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/freshcart-grocery': {
      id: '/demo/freshcart-grocery'
      path: '/demo/freshcart-grocery'
      fullPath: '/demo/freshcart-grocery'
      preLoaderRoute: typeof DemoFreshcartGroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/eduprime-lms': {
      id: '/demo/eduprime-lms'
      path: '/demo/eduprime-lms'
      fullPath: '/demo/eduprime-lms'
      preLoaderRoute: typeof DemoEduprimeLmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/brandkit-design': {
      id: '/demo/brandkit-design'
      path: '/demo/brandkit-design'
      fullPath: '/demo/brandkit-design'
      preLoaderRoute: typeof DemoBrandkitDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config': {
      id: '/api/public/config'
      path: '/api/public/config'
      fullPath: '/api/public/config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DemoBrandkitDesignRoute: DemoBrandkitDesignRoute,
  DemoEduprimeLmsRoute: DemoEduprimeLmsRoute,
  DemoFreshcartGroceryRoute: DemoFreshcartGroceryRoute,
  DemoKartplusEcommerceRoute: DemoKartplusEcommerceRoute,
  DemoLuxeLandingRoute: DemoLuxeLandingRoute,
  DemoOrbitCrmRoute: DemoOrbitCrmRoute,
  DemoPanelproSmmRoute: DemoPanelproSmmRoute,
  DemoPulseadsVideoRoute: DemoPulseadsVideoRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
