/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services.software-development'
import { Route as ServicesSmmPanelWebsiteRouteImport } from './routes/services.smm-panel-website'
import { Route as ServicesReadymadeEcommerceWebsiteRouteImport } from './routes/services.readymade-ecommerce-website'
import { Route as ServicesLogoCoverPosterDesignRouteImport } from './routes/services.logo-cover-poster-design'
import { Route as ServicesLmsSiteDevelopmentRouteImport } from './routes/services.lms-site-development'
import { Route as ServicesLandingPageDesignRouteImport } from './routes/services.landing-page-design'
import { Route as ServicesFacebookPixelSetupRouteImport } from './routes/services.facebook-pixel-setup'
import { Route as ServicesFacebookBusinessPageSetupRouteImport } from './routes/services.facebook-business-page-setup'
import { Route as ServicesEcommerceWebsiteDesignRouteImport } from './routes/services.ecommerce-website-design'
import { Route as ServicesCustomWebsitesRouteImport } from './routes/services.custom-websites'
import { Route as ServicesAiVideoAdsRouteImport } from './routes/services.ai-video-ads'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as DemoPulseadsVideoRouteImport } from './routes/demo.pulseads-video'
import { Route as DemoPanelproSmmRouteImport } from './routes/demo.panelpro-smm'
import { Route as DemoOrbitCrmRouteImport } from './routes/demo.orbit-crm'
import { Route as DemoLuxeLandingRouteImport } from './routes/demo.luxe-landing'
import { Route as DemoKartplusEcommerceRouteImport } from './routes/demo.kartplus-ecommerce'
import { Route as DemoFreshcartGroceryRouteImport } from './routes/demo.freshcart-grocery'
import { Route as DemoEduprimeLmsRouteImport } from './routes/demo.eduprime-lms'
import { Route as DemoBrandkitDesignRouteImport } from './routes/demo.brandkit-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/services/software-development',
    path: '/services/software-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSmmPanelWebsiteRoute = ServicesSmmPanelWebsiteRouteImport.update({
  id: '/services/smm-panel-website',
  path: '/services/smm-panel-website',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesReadymadeEcommerceWebsiteRoute =
  ServicesReadymadeEcommerceWebsiteRouteImport.update({
    id: '/services/readymade-ecommerce-website',
    path: '/services/readymade-ecommerce-website',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLogoCoverPosterDesignRoute =
  ServicesLogoCoverPosterDesignRouteImport.update({
    id: '/services/logo-cover-poster-design',
    path: '/services/logo-cover-poster-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLmsSiteDevelopmentRoute =
  ServicesLmsSiteDevelopmentRouteImport.update({
    id: '/services/lms-site-development',
    path: '/services/lms-site-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesLandingPageDesignRoute =
  ServicesLandingPageDesignRouteImport.update({
    id: '/services/landing-page-design',
    path: '/services/landing-page-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFacebookPixelSetupRoute =
  ServicesFacebookPixelSetupRouteImport.update({
    id: '/services/facebook-pixel-setup',
    path: '/services/facebook-pixel-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFacebookBusinessPageSetupRoute =
  ServicesFacebookBusinessPageSetupRouteImport.update({
    id: '/services/facebook-business-page-setup',
    path: '/services/facebook-business-page-setup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEcommerceWebsiteDesignRoute =
  ServicesEcommerceWebsiteDesignRouteImport.update({
    id: '/services/ecommerce-website-design',
    path: '/services/ecommerce-website-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesCustomWebsitesRoute = ServicesCustomWebsitesRouteImport.update({
  id: '/services/custom-websites',
  path: '/services/custom-websites',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAiVideoAdsRoute = ServicesAiVideoAdsRouteImport.update({
  id: '/services/ai-video-ads',
  path: '/services/ai-video-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPulseadsVideoRoute = DemoPulseadsVideoRouteImport.update({
  id: '/demo/pulseads-video',
  path: '/demo/pulseads-video',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPanelproSmmRoute = DemoPanelproSmmRouteImport.update({
  id: '/demo/panelpro-smm',
  path: '/demo/panelpro-smm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoOrbitCrmRoute = DemoOrbitCrmRouteImport.update({
  id: '/demo/orbit-crm',
  path: '/demo/orbit-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLuxeLandingRoute = DemoLuxeLandingRouteImport.update({
  id: '/demo/luxe-landing',
  path: '/demo/luxe-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoKartplusEcommerceRoute = DemoKartplusEcommerceRouteImport.update({
  id: '/demo/kartplus-ecommerce',
  path: '/demo/kartplus-ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFreshcartGroceryRoute = DemoFreshcartGroceryRouteImport.update({
  id: '/demo/freshcart-grocery',
  path: '/demo/freshcart-grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoEduprimeLmsRoute = DemoEduprimeLmsRouteImport.update({
  id: '/demo/eduprime-lms',
  path: '/demo/eduprime-lms',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBrandkitDesignRoute = DemoBrandkitDesignRouteImport.update({
  id: '/demo/brandkit-design',
  path: '/demo/brandkit-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/brandkit-design': typeof DemoBrandkitDesignRoute
  '/demo/eduprime-lms': typeof DemoEduprimeLmsRoute
  '/demo/freshcart-grocery': typeof DemoFreshcartGroceryRoute
  '/demo/kartplus-ecommerce': typeof DemoKartplusEcommerceRoute
  '/demo/luxe-landing': typeof DemoLuxeLandingRoute
  '/demo/orbit-crm': typeof DemoOrbitCrmRoute
  '/demo/panelpro-smm': typeof DemoPanelproSmmRoute
  '/demo/pulseads-video': typeof DemoPulseadsVideoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-video-ads': typeof ServicesAiVideoAdsRoute
  '/services/custom-websites': typeof ServicesCustomWebsitesRoute
  '/services/ecommerce-website-design': typeof ServicesEcommerceWebsiteDesignRoute
  '/services/facebook-business-page-setup': typeof ServicesFacebookBusinessPageSetupRoute
  '/services/facebook-pixel-setup': typeof ServicesFacebookPixelSetupRoute
  '/services/landing-page-design': typeof ServicesLandingPageDesignRoute
  '/services/lms-site-development': typeof ServicesLmsSiteDevelopmentRoute
  '/services/logo-cover-poster-design': typeof ServicesLogoCoverPosterDesignRoute
  '/services/readymade-ecommerce-website': typeof ServicesReadymadeEcommerceWebsiteRoute
  '/services/smm-panel-website': typeof ServicesSmmPanelWebsiteRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/brandkit-design': typeof DemoBrandkitDesignRoute
  '/demo/eduprime-lms': typeof DemoEduprimeLmsRoute
  '/demo/freshcart-grocery': typeof DemoFreshcartGroceryRoute
  '/demo/kartplus-ecommerce': typeof DemoKartplusEcommerceRoute
  '/demo/luxe-landing': typeof DemoLuxeLandingRoute
  '/demo/orbit-crm': typeof DemoOrbitCrmRoute
  '/demo/panelpro-smm': typeof DemoPanelproSmmRoute
  '/demo/pulseads-video': typeof DemoPulseadsVideoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-video-ads': typeof ServicesAiVideoAdsRoute
  '/services/custom-websites': typeof ServicesCustomWebsitesRoute
  '/services/ecommerce-website-design': typeof ServicesEcommerceWebsiteDesignRoute
  '/services/facebook-business-page-setup': typeof ServicesFacebookBusinessPageSetupRoute
  '/services/facebook-pixel-setup': typeof ServicesFacebookPixelSetupRoute
  '/services/landing-page-design': typeof ServicesLandingPageDesignRoute
  '/services/lms-site-development': typeof ServicesLmsSiteDevelopmentRoute
  '/services/logo-cover-poster-design': typeof ServicesLogoCoverPosterDesignRoute
  '/services/readymade-ecommerce-website': typeof ServicesReadymadeEcommerceWebsiteRoute
  '/services/smm-panel-website': typeof ServicesSmmPanelWebsiteRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/brandkit-design': typeof DemoBrandkitDesignRoute
  '/demo/eduprime-lms': typeof DemoEduprimeLmsRoute
  '/demo/freshcart-grocery': typeof DemoFreshcartGroceryRoute
  '/demo/kartplus-ecommerce': typeof DemoKartplusEcommerceRoute
  '/demo/luxe-landing': typeof DemoLuxeLandingRoute
  '/demo/orbit-crm': typeof DemoOrbitCrmRoute
  '/demo/panelpro-smm': typeof DemoPanelproSmmRoute
  '/demo/pulseads-video': typeof DemoPulseadsVideoRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-video-ads': typeof ServicesAiVideoAdsRoute
  '/services/custom-websites': typeof ServicesCustomWebsitesRoute
  '/services/ecommerce-website-design': typeof ServicesEcommerceWebsiteDesignRoute
  '/services/facebook-business-page-setup': typeof ServicesFacebookBusinessPageSetupRoute
  '/services/facebook-pixel-setup': typeof ServicesFacebookPixelSetupRoute
  '/services/landing-page-design': typeof ServicesLandingPageDesignRoute
  '/services/lms-site-development': typeof ServicesLmsSiteDevelopmentRoute
  '/services/logo-cover-poster-design': typeof ServicesLogoCoverPosterDesignRoute
  '/services/readymade-ecommerce-website': typeof ServicesReadymadeEcommerceWebsiteRoute
  '/services/smm-panel-website': typeof ServicesSmmPanelWebsiteRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/brandkit-design'
    | '/demo/eduprime-lms'
    | '/demo/freshcart-grocery'
    | '/demo/kartplus-ecommerce'
    | '/demo/luxe-landing'
    | '/demo/orbit-crm'
    | '/demo/panelpro-smm'
    | '/demo/pulseads-video'
    | '/services/$slug'
    | '/services/ai-video-ads'
    | '/services/custom-websites'
    | '/services/ecommerce-website-design'
    | '/services/facebook-business-page-setup'
    | '/services/facebook-pixel-setup'
    | '/services/landing-page-design'
    | '/services/lms-site-development'
    | '/services/logo-cover-poster-design'
    | '/services/readymade-ecommerce-website'
    | '/services/smm-panel-website'
    | '/services/software-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/brandkit-design'
    | '/demo/eduprime-lms'
    | '/demo/freshcart-grocery'
    | '/demo/kartplus-ecommerce'
    | '/demo/luxe-landing'
    | '/demo/orbit-crm'
    | '/demo/panelpro-smm'
    | '/demo/pulseads-video'
    | '/services/$slug'
    | '/services/ai-video-ads'
    | '/services/custom-websites'
    | '/services/ecommerce-website-design'
    | '/services/facebook-business-page-setup'
    | '/services/facebook-pixel-setup'
    | '/services/landing-page-design'
    | '/services/lms-site-development'
    | '/services/logo-cover-poster-design'
    | '/services/readymade-ecommerce-website'
    | '/services/smm-panel-website'
    | '/services/software-development'
  id:
    | '__root__'
    | '/'
    | '/demo/brandkit-design'
    | '/demo/eduprime-lms'
    | '/demo/freshcart-grocery'
    | '/demo/kartplus-ecommerce'
    | '/demo/luxe-landing'
    | '/demo/orbit-crm'
    | '/demo/panelpro-smm'
    | '/demo/pulseads-video'
    | '/services/$slug'
    | '/services/ai-video-ads'
    | '/services/custom-websites'
    | '/services/ecommerce-website-design'
    | '/services/facebook-business-page-setup'
    | '/services/facebook-pixel-setup'
    | '/services/landing-page-design'
    | '/services/lms-site-development'
    | '/services/logo-cover-poster-design'
    | '/services/readymade-ecommerce-website'
    | '/services/smm-panel-website'
    | '/services/software-development'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoBrandkitDesignRoute: typeof DemoBrandkitDesignRoute
  DemoEduprimeLmsRoute: typeof DemoEduprimeLmsRoute
  DemoFreshcartGroceryRoute: typeof DemoFreshcartGroceryRoute
  DemoKartplusEcommerceRoute: typeof DemoKartplusEcommerceRoute
  DemoLuxeLandingRoute: typeof DemoLuxeLandingRoute
  DemoOrbitCrmRoute: typeof DemoOrbitCrmRoute
  DemoPanelproSmmRoute: typeof DemoPanelproSmmRoute
  DemoPulseadsVideoRoute: typeof DemoPulseadsVideoRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesAiVideoAdsRoute: typeof ServicesAiVideoAdsRoute
  ServicesCustomWebsitesRoute: typeof ServicesCustomWebsitesRoute
  ServicesEcommerceWebsiteDesignRoute: typeof ServicesEcommerceWebsiteDesignRoute
  ServicesFacebookBusinessPageSetupRoute: typeof ServicesFacebookBusinessPageSetupRoute
  ServicesFacebookPixelSetupRoute: typeof ServicesFacebookPixelSetupRoute
  ServicesLandingPageDesignRoute: typeof ServicesLandingPageDesignRoute
  ServicesLmsSiteDevelopmentRoute: typeof ServicesLmsSiteDevelopmentRoute
  ServicesLogoCoverPosterDesignRoute: typeof ServicesLogoCoverPosterDesignRoute
  ServicesReadymadeEcommerceWebsiteRoute: typeof ServicesReadymadeEcommerceWebsiteRoute
  ServicesSmmPanelWebsiteRoute: typeof ServicesSmmPanelWebsiteRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/services/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/smm-panel-website': {
      id: '/services/smm-panel-website'
      path: '/services/smm-panel-website'
      fullPath: '/services/smm-panel-website'
      preLoaderRoute: typeof ServicesSmmPanelWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/readymade-ecommerce-website': {
      id: '/services/readymade-ecommerce-website'
      path: '/services/readymade-ecommerce-website'
      fullPath: '/services/readymade-ecommerce-website'
      preLoaderRoute: typeof ServicesReadymadeEcommerceWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/logo-cover-poster-design': {
      id: '/services/logo-cover-poster-design'
      path: '/services/logo-cover-poster-design'
      fullPath: '/services/logo-cover-poster-design'
      preLoaderRoute: typeof ServicesLogoCoverPosterDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/lms-site-development': {
      id: '/services/lms-site-development'
      path: '/services/lms-site-development'
      fullPath: '/services/lms-site-development'
      preLoaderRoute: typeof ServicesLmsSiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/landing-page-design': {
      id: '/services/landing-page-design'
      path: '/services/landing-page-design'
      fullPath: '/services/landing-page-design'
      preLoaderRoute: typeof ServicesLandingPageDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/facebook-pixel-setup': {
      id: '/services/facebook-pixel-setup'
      path: '/services/facebook-pixel-setup'
      fullPath: '/services/facebook-pixel-setup'
      preLoaderRoute: typeof ServicesFacebookPixelSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/facebook-business-page-setup': {
      id: '/services/facebook-business-page-setup'
      path: '/services/facebook-business-page-setup'
      fullPath: '/services/facebook-business-page-setup'
      preLoaderRoute: typeof ServicesFacebookBusinessPageSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ecommerce-website-design': {
      id: '/services/ecommerce-website-design'
      path: '/services/ecommerce-website-design'
      fullPath: '/services/ecommerce-website-design'
      preLoaderRoute: typeof ServicesEcommerceWebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/custom-websites': {
      id: '/services/custom-websites'
      path: '/services/custom-websites'
      fullPath: '/services/custom-websites'
      preLoaderRoute: typeof ServicesCustomWebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ai-video-ads': {
      id: '/services/ai-video-ads'
      path: '/services/ai-video-ads'
      fullPath: '/services/ai-video-ads'
      preLoaderRoute: typeof ServicesAiVideoAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/pulseads-video': {
      id: '/demo/pulseads-video'
      path: '/demo/pulseads-video'
      fullPath: '/demo/pulseads-video'
      preLoaderRoute: typeof DemoPulseadsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/panelpro-smm': {
      id: '/demo/panelpro-smm'
      path: '/demo/panelpro-smm'
      fullPath: '/demo/panelpro-smm'
      preLoaderRoute: typeof DemoPanelproSmmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/orbit-crm': {
      id: '/demo/orbit-crm'
      path: '/demo/orbit-crm'
      fullPath: '/demo/orbit-crm'
      preLoaderRoute: typeof DemoOrbitCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/luxe-landing': {
      id: '/demo/luxe-landing'
      path: '/demo/luxe-landing'
      fullPath: '/demo/luxe-landing'
      preLoaderRoute: typeof DemoLuxeLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/kartplus-ecommerce': {
      id: '/demo/kartplus-ecommerce'
      path: '/demo/kartplus-ecommerce'
      fullPath: '/demo/kartplus-ecommerce'
      preLoaderRoute: typeof DemoKartplusEcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/freshcart-grocery': {
      id: '/demo/freshcart-grocery'
      path: '/demo/freshcart-grocery'
      fullPath: '/demo/freshcart-grocery'
      preLoaderRoute: typeof DemoFreshcartGroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/eduprime-lms': {
      id: '/demo/eduprime-lms'
      path: '/demo/eduprime-lms'
      fullPath: '/demo/eduprime-lms'
      preLoaderRoute: typeof DemoEduprimeLmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/brandkit-design': {
      id: '/demo/brandkit-design'
      path: '/demo/brandkit-design'
      fullPath: '/demo/brandkit-design'
      preLoaderRoute: typeof DemoBrandkitDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoBrandkitDesignRoute: DemoBrandkitDesignRoute,
  DemoEduprimeLmsRoute: DemoEduprimeLmsRoute,
  DemoFreshcartGroceryRoute: DemoFreshcartGroceryRoute,
  DemoKartplusEcommerceRoute: DemoKartplusEcommerceRoute,
  DemoLuxeLandingRoute: DemoLuxeLandingRoute,
  DemoOrbitCrmRoute: DemoOrbitCrmRoute,
  DemoPanelproSmmRoute: DemoPanelproSmmRoute,
  DemoPulseadsVideoRoute: DemoPulseadsVideoRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesAiVideoAdsRoute: ServicesAiVideoAdsRoute,
  ServicesCustomWebsitesRoute: ServicesCustomWebsitesRoute,
  ServicesEcommerceWebsiteDesignRoute: ServicesEcommerceWebsiteDesignRoute,
  ServicesFacebookBusinessPageSetupRoute:
    ServicesFacebookBusinessPageSetupRoute,
  ServicesFacebookPixelSetupRoute: ServicesFacebookPixelSetupRoute,
  ServicesLandingPageDesignRoute: ServicesLandingPageDesignRoute,
  ServicesLmsSiteDevelopmentRoute: ServicesLmsSiteDevelopmentRoute,
  ServicesLogoCoverPosterDesignRoute: ServicesLogoCoverPosterDesignRoute,
  ServicesReadymadeEcommerceWebsiteRoute:
    ServicesReadymadeEcommerceWebsiteRoute,
  ServicesSmmPanelWebsiteRoute: ServicesSmmPanelWebsiteRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
